### ISSUE TITLE
How to install wine on Ubuntu 18.04

### ISSUE THREAD

**Issue by username1565** [ValveSoftware/wine#105]
Hello. I did try to install `wine-stable` on ubuntu 18.04,
but I see the following errors:
```
Preparing to unpack .../wine-stable-i386_6.0.0~bionic-1_i386.deb ...
Unpacking wine-stable-i386:i386 (6.0.0~bionic-1) ...
dpkg: error processing archive /var/cache/apt/archives/wine-stable-i386_6.0.0~bionic-1_i386.deb (--unpack):
unable to securely remove '/opt/wine-stable/lib/wine/regedit.exe.dpkg-new': Invalid argument
dpkg-deb: error: paste subprocess was killed by signal (Broken pipe)
Errors were encountered while processing:
/var/cache/apt/archives/wine-stable-i386_6.0.0~bionic-1_i386.deb
```
I did go to /opt/wine-stable/lib/wine/
and see there, this:
```
user@comp:/opt/wine-stable/lib/wine$ dir
regedit.exe.dpkg-new regsvr32.exe.dpkg-new
```
two files, and this can not be deleted, using `sudo rm -rf -- *`?

How to install wine 6.0 or another stable version, on Ubuntu 18.04?
Or compile from the source code...

**Comment by kisak-valve** [comment]
Hello @username1565, this repo and issue tracker is for a fork of wine found in Proton. Upstream wine's packaging is out of scope for this issue tracker.

Your best bet for support with upstream wine is either asking around your distro's community, or https://www.winehq.org/.
