### ISSUE TITLE
Backport caching for display mode querying

### ISSUE THREAD

**Issue by tannisroot** [ValveSoftware/wine#117]
See https://bugs.winehq.org/show_bug.cgi?id=51047
https://source.winehq.org/git/wine.git/commit/095bdc6
https://source.winehq.org/git/wine.git/commit/7fabcf6
(although these patches are a part of a series and it might be best to backport them all:
https://source.winehq.org/git/wine.git/commit/d7cd5587df5c0dfc6a5b0b9586b0feee28ee0de8
https://source.winehq.org/git/wine.git/commit/ab431c70b4537ce62ead8d79939d801932327159
https://source.winehq.org/git/wine.git/commit/59e5a8d055f28bde9f53354cd250a641d84b9a51
https://source.winehq.org/git/wine.git/commit/9b2f59cb94d5aa7b8fbe4e0373d933a630b51dc1).

I realize that the bug report references The Sims 2, a game not available on Steam, but I can imagine this affects more than just that game.

**Comment by aeikum** [comment]
We already have those two commits in proton_6.3, see 41856feafc0efbde429b15ccca30218e26d5992a and 2d19dc0c788ed5efd60d75e3c7bccbcde2df19eb. Do you expect the other four to help, too?

**Comment by tannisroot** [comment]
I sincerely apologize, I must have been looking at an outdated branch when checking if these commits are present in Proton, and apparently I used older (6.3-4 i guess?) when testing if the issue is present.
Closing.

**Comment by aeikum** [comment]
No problem. Looks like they were just added in 6.3-5, so you didn't miss them by much.
