### ISSUE TITLE
6.3-6 Prefix Issue ?

### ISSUE THREAD

**Issue by liberodark** [ValveSoftware/wine#122]
Hi,

Have see a strange prefix creation.
In 6.3-5 : 
`drive_c/users/steamuser/Application Data` exist
In 6.3-6 : 
`drive_c/users/steamuser/Application Data` not exist
After update to wine-proton 6.3-6 some games lost save.

Full Compare : 
6.3-5
```
AppData
Application Data
Contacts
Cookies
Desktop
Downloads
Favorites
Links
Local Settings
My Documents
My Music
My Pictures
My Videos
NetHood
PrintHood
Recent
Saved Games
Searches
SendTo
Start Menu
Temp
Templates
```

6.3-6
```
AppData
Contacts
Desktop
Documents
Downloads
Favorites
Links
Music
My Documents
My Music
My Pictures
My Videos
Pictures
Saved Games
Searches
Temp
Templates
Videos
```

Best Regards

**Comment by kakra** [comment]
This may be due to https://github.com/ValveSoftware/Proton/commit/e82e98b1ff1544acb4b80b8e1b8e42b4f1531346 and you may need to verify that the symlink exists and the saved games moved to the correct location. `Application Data` be a symlink pointing to `AppData/Roaming`.

**Comment by liberodark** [comment]
I saw this point there but the problem is still boring for the users. 
-  `AppData/Roaming`

**Comment by kakra** [comment]
How did you create the listing? `Application Data` should be a symlink, just listing directories won't tell the whole story.

It migrated properly for me, saved games may be in `My Documents BACKUP` or `Application Data BACKUP`.

**Comment by kakra** [comment]
BTW: It's probably not a wine issue but a Proton issue, maybe the issue should be moved? @aeikum

**Comment by liberodark** [comment]
Im not using proton but wine-proton.

**Comment by liberodark** [comment]
That is a change on prefix on wine i think that have been upstream to wine too.
Because on wine 6.14 you can see the same change.

**Comment by kakra** [comment]
There's no official wine-proton. This wine version should be used with the Proton launcher only - and that's probably where things went wrong now: The Proton launcher actually does the proper migration steps. Using wine-proton standalone is probably missing that part.

**Comment by liberodark** [comment]
I saw this commit also I try to understand especially why this change on wine part. https://github.com/ValveSoftware/Proton/commit/e82e98b1ff1544acb4b80b8e1b8e42b4f1531346

**Comment by kakra** [comment]
The new-style shell directories were introduced in wine 6.10: https://github.com/wine-mirror/wine/commits/wine-6.10?author=aeikum

Doesn't look like it's supposed to do any proper migration unless there's some hidden magic somewhere. This probably means you're required to do the migration by yourself. In the case of Proton, that's what the proton launcher does. Third-party tools using proton or wine beyond 6.10 should probably do a similar migration.

**Comment by liberodark** [comment]
Ok good thank for information.

**Comment by kakra** [comment]
It's important to note that wine-proton from Valve should not be compiled as-is and used outside of Steam. You'd need to remove at least the steamlib proxy commits, and probably also some commits handling profile directory stuff - because that's working differently in Proton, e.g. the user is always called "steamuser" while wine-upstream uses the unix username. Such patches need to be excluded if you plan to use wine-proton standalone.

**Comment by liberodark** [comment]
Yes i know that.

**Comment by liberodark** [comment]
Have fixed the issue on my side
