### ISSUE TITLE
err:ole:start_rpcss Failed to start RpcSs service

### ISSUE THREAD

**Issue by agrajag9** [ValveSoftware/wine#134]
Some games fail to launch with this error which may be fixed upstream in e6407c39bab62838081f30868cb2ac1362029bdf:

https://bugs.winehq.org/show_bug.cgi?id=50168

https://source.winehq.org/git/wine.git/commitdiff/e6407c39bab62838081f30868cb2ac1362029bdf

DOOM Eternal crashes with the following:

```
007c:fixme:msg:ChangeWindowMessageFilterEx 000000000002006A c06f 1 0000000000000000
007c:fixme:ntdll:create_logical_proc_info stub
0090:fixme:fsync:do_fsync futexes not supported on this platform.
0090:warn:module:load_builtin_dll cannot find builtin library for L"\\??\\Z:\\usr\\home\\steam\\.steam\\steam\\steamapps\\common\\DOOMEternal\\bink2w64.dll"
0090:warn:module:alloc_module disabling no-exec because of L"bink2w64.dll"
0090:warn:module:load_builtin_dll cannot find builtin library for L"\\??\\Z:\\usr\\home\\steam\\.steam\\steam\\steamapps\\common\\DOOMEternal\\oo2core_8_win64.dll"
0090:warn:module:load_builtin_dll cannot find builtin library for L"\\??\\Z:\\usr\\home\\steam\\.steam\\steam\\steamapps\\common\\DOOMEternal\\steam_api64.dll"
0090:fixme:heap:RtlSetHeapInformation 0000000001130000 0 000000000092EC60 4 stub
0090:warn:module:load_builtin_dll cannot find builtin library for L"\\??\\C:\\windows\\system32\\dtdata.dll"
0090:warn:module:load_dll Failed to load module L"dtdata.dll"; status=c0000135
007c:fixme:kernelbase:AppPolicyGetProcessTerminationMethod FFFFFFFFFFFFFFFA, 000000000092FD50
004c:err:ole:start_rpcss Failed to start RpcSs service
```

**Comment by aeikum** [comment]
Thanks for the suggestion, I'll apply that commit. If you don't mind me asking, what distro & kernel version are you running?

**Comment by agrajag9** [comment]
Not your average user...

freebsd/freebsd-src@c0163f4abef

Our port freebsd/freebsd-ports@9b46ada11cb643d07d33cd5ce10ae155fbcd0e3e is currently pointed at 97f962cd469ee9b9b68d32e79849bf94cfe15581 so we're only a bit behind :)

**Comment by aeikum** [comment]
Neat! Cool to hear Proton's patchset is generally useful over there. Been a while since I worked with a BSD, for our OSS driver :)

**Comment by gh503** [comment]
i get the same trouble above.
```txt
─$ wine WINEDEBUG=err+warn+fixme+trace start /i wine-mono-7.4.0-x86.msi    
wine: Call from 000000007B013D7E to unimplemented function ndis.sys.NdisGetVersion, aborting
wine: Unimplemented function ndis.sys.NdisGetVersion called at address 000000007B013D7E (thread 00bc), starting debugger...
00e0:err:ole:start_rpcss Failed to start RpcSs service
0094:err:ole:start_rpcss Failed to start RpcSs service
003c:err:service:process_send_command receiving command result timed out
无法启动程序，或者没有为指定文件关联应用程序。
ShellExecuteEx 失败: 找不到文件。
```

my laptop:
```
$ u                             
Linux angusrobot 6.0.0-kali6-amd64 #1 SMP PREEMPT_DYNAMIC Debian 6.0.12-1kali1 (2022-12-19) x86_64 GNU/Linux
      
$ wine --version                                                      
wine-8.0 (Debian 8.0~repack-1)
             
```

**Comment by kisak-valve** [comment]
Hello @angusrobot, `Unimplemented function ndis.sys.NdisGetVersion` is your issue, and is unrelated to the issue reported here.

Friendly note that you have come across a downstream fork of wine which is used as part of Proton. You're using an upstream version of wine and feedback on how applications using it should be sent upstream as well. (https://bugs.winehq.org/)

It looks like https://github.com/ValveSoftware/wine/commit/e6407c39bab62838081f30868cb2ac1362029bdf is part of Proton 7.0, so this issue report is outdated.
