### ISSUE TITLE
`winevulkan: Allow call of unexposed function vkCmdWriteBufferMarkerAMD. ` is no longer needed.

### ISSUE THREAD

**Issue by DadSchoorse** [ValveSoftware/wine#135]
a68c514399374b01d79f9d96ab1daa69380f9a16 shouldn't be needed anymore because proton now includes my proper fix fc8dcb53c2cebf9a08d9c49a4f7fc021b79fc819.

**Comment by ivyl** [comment]
I've pushed a revert to our development branch so we won't forget to yank out the hack the next rebase. Thanks!
