### ISSUE TITLE
[Question] Should I report issues with Wine here?

### ISSUE THREAD

**Issue by SeanRamey** [ValveSoftware/wine#149]
I'm using Bottles as my "frontend" for using Wine (and some versions of Proton as well). The official bugzilla site for Wine is honestly just such garbage to use. Should I report issues here instead, or maybe in ValveSoftware/Proton?

**Comment by kisak-valve** [comment]
Hello @SeanRamey, no, only issues with Proton-specific modifications to wine are relevant here. The rest should be evaluated upstream.
