### ISSUE TITLE
bug: bcrypt_main.c is missing an implementation for CFB!

### ISSUE THREAD

**Issue by icf3ver** [ValveSoftware/wine#153]
Hi
In [bcrypt_main:642](https://github.com/wine-mirror/wine/blob/1d178982ae5a73b18f367026c8689b56789c39fd/dlls/bcrypt/bcrypt_main.c#L642), and potentially elsewhere, there is a [CFB (ciphertext feedback)](https://en.wikipedia.org/wiki/Block_cipher_mode_of_operation#Cipher_feedback_(CFB)) implementation missing.  Defined [here](https://github.com/wine-mirror/wine/blob/1d178982ae5a73b18f367026c8689b56789c39fd/include/bcrypt.h#L106) this seems to be a major oversight. Please fix this. 

Best Regards
@nnmarcoo and littletitan

**Comment by kisak-valve** [comment]
Hello @littleTitan, you've come across a downstream fork of wine used in Proton. This doesn't read like a Proton-specific issue and you should bring this to the attention of wine devs in the [upstream bug tracker](https://bugs.winehq.org/).

**Comment by icf3ver** [comment]
Thanks for the pointer. Will do. (Done)
