### ISSUE TITLE
configure doesn't run correctly

### ISSUE THREAD

**Issue by Derpalus** [ValveSoftware/wine#154]
I'm trying to build this version of wine in a container. Here is the docker file (as far as I've come):
```
FROM ubuntu:20.04

ARG DEBIAN_FRONTEND=noninteractive
RUN set -xe					&& \
	# add 32-bit support
	dpkg --add-architecture i386		&& \
	#
	apt-get -qq update					&& \
	apt-get -yqq upgrade				&& \
	#
	apt-get -yqq install			\
		apt-transport-https software-properties-common wget	git					&& \
	#
	git clone https://github.com/ValveSoftware/wine.git
	#git clone https://gitlab.winehq.org/wine/wine.git

ARG DEBIAN_FRONTEND=noninteractive
RUN set -xe		&& \
	# Setup dependencies
	sed -i.bak 's/^# *deb-src/deb-src/g' /etc/apt/sources.list && \
  	apt-get update	&& \
	apt-get -yqq build-dep wine

ARG DEBIAN_FRONTEND=noninteractive
RUN set -xe		&& \
	mkdir wine64-build && cd wine64-build	&& \
	../wine/configure --enable-win64
```

The error I get is this:
```
checking for __clear_cache... yes
checking whether we need to define __x86_64__... no
creating Makefile rules... done
configure: creating ./config.status
config.status: creating include/config.h
config.status: linking ../wine/tools/winewrapper to wine
config.status: linking ../wine/tools/winewrapper to wine64
config.status: executing include/stamp-h commands
config.status: executing tools/makedep commands
config.status: executing Makefile commands
../wine/dlls/amd_ags_x64/amd_ags_x64_main.c:10: error: wine/vulkan.h: No such file or directory
config.status: error: could not create Makefile
```

Now I would have reported this in the normal wine repo, but that one configures perfectly fine (test it by switching the repositories in the first RUN statement). So the only conclusion I can make is that something is wrong with the configure file in this version of wine.

As there are no instructions about anything one should do differently from the normal wine repo I've just followed the instructions for that one, which gives me this error.

**Comment by ivyl** [comment]
This repository is not meant to be built as a standalone. It's a part of Proton. Unlike upstream we don't ship (most of) the  autogenerated files. This helps with cherry-picks / backports - resolving conflicts on configure / vulkan thunks / wineserver protocol is painful.

https://github.com/ValveSoftware/Proton/blob/proton_7.0/make/rules-autoconf.mk#L12
https://github.com/ValveSoftware/Proton/blob/proton_7.0/Makefile.in#L707

For instructions on how to build Proton see https://github.com/ValveSoftware/Proton/#building-proton
