### ISSUE TITLE
Bad system call (core dumped)

### ISSUE THREAD

**Issue by system-failure-b8xy** [ValveSoftware/wine#167]
After I installed Wine from the Ubuntu repositories and tried to run it, I get this error:

```
main.sh: line 1:    389 Bad system call                (core dumped) wine ./ScratchInstaller1.4.exe
exit status 159
```
This has worked before, but it just started giving me this error all of a sudden.

I am using Replit on Chrome, on a boosted Repl.
Please help!

**Comment by kisak-valve** [comment]
Hello @JustinsKittens, you've come across a downstream repo of wine used in the [Proton](https://github.com/ValveSoftware/Proton) fork of wine. It is unrelated to your system installed wine instance.

You'll want to post this feedback in https://bugs.winehq.org/ for the upstream wine devs to ponder.
