### ISSUE TITLE
[Question&Request] strong expectations for wechat, qq 

### ISSUE THREAD

**Issue by gh503** [ValveSoftware/wine#183]
winehq is a greatful software, I love it!

In China, we usually use the ims software like wechat, qq which not supported well on linux platform. And the company tencent has not the plan to publish the linux version.

Emmm, I've seen the old version of qq adapted on winehq. Is there any plan for wechat or qq?

thanks very much.

yours,

**Comment by kisak-valve** [comment]
Hello @angusrobot, you've come across a downstream fork of wine found in Proton, a compatibility tool for Steam.

You'll want to ask this question to the upstream project. (https://www.winehq.org/)
