### ISSUE TITLE
Request: Add "Removable" drive mount type

### ISSUE THREAD

**Issue by TheKayThatWasOrange** [ValveSoftware/wine#185]
I've come across a number of firmware updating apps for various devices which perform pretty basic filesystem writes to the hardware when it's put into mass storage mode, but they will not work unless the drive itself is of the "Removable" type according to this method in .NET:

https://learn.microsoft.com/en-us/dotnet/api/system.io.driveinfo.drivetype?view=net-8.0

Even though the virtual drive mounts and is perfectly accessible,  unless that method returns a `2`, the app is just going to choose to ignore it. 

I realize that this may sound a little esoteric and that there could be a tremendous amount of Registry complexity involved in satisfying that method, but given that the current list of drive types we have to choose from in winecfg is basically from 1993, it seems like a bit of an update could be a generally good idea for the project as a whole if it is at all feasible. The "modern" list is honestly not all that different:

https://learn.microsoft.com/en-us/dotnet/api/system.io.drivetype?view=net-8.0

**Comment by kisak-valve** [comment]
Hello @TheKayThatWasOrange, you've come across a downstream fork of wine used in the Proton project. This feedback should go to the upstream wine project at https://bugs.winehq.org/.

**Comment by TheKayThatWasOrange** [comment]
Thanks, but their Bugzilla thing is completely broken and will not allow me to register so that's not going to happen.
