### ISSUE TITLE
wine-8.0.1c unable to load fonts

### ISSUE THREAD

**Issue by ExecutorElassus** [ValveSoftware/wine#187]
When trying to start EVE Online's launcher, I get the following error right before it crashes out:

```
[32:36:0419/170207.119:ERROR:network_change_notifier_win.cc(142)] WSALookupServiceBegin failed with: 8
ALSA lib /var/tmp/portage/media-libs/alsa-lib-1.2.8-r1/work/alsa-lib-1.2.8/src/pcm/pcm_dmix.c:972:(snd_pcm_dmix_open) The dmix plugin supports only playback stream
[32:36:0419/170208.962:ERROR:platform_font_skia.cc(343)] Could not find any font: Tahoma, sans. Falling back to the default
carrier0/evelog.sh: line 26: 10006 Killed                  wine /home/elassus/carrier0/EVE-win/Launcher/evelauncher.exe
```

The "could not find any font" error message pops up a second before the launcher closes, so that's all I have to go on. Downgrading to wine-proton-7.0.6 results in the launcher starting and being able to run the EVE client without issue. I don't have winetricks/protontricks installed. 

Is there any other info you need?

**Comment by ivyl** [comment]
I've just tried EVE Online with Proton 8.0 and it seems to be fine. The Steam version that is.

```
Proton 8.0 $ fd tahoma
dist/share/wine/fonts/tahoma.ttf
dist/share/wine/fonts/tahomabd.ttf
```

Are you building this version of Wine and try to use it outside of Proton? It's not really supported or tested and you are mostly on your own.

FWIW Tahoma-compatible font we are using is distributed with Wine https://github.com/ValveSoftware/wine/tree/proton_8.0/fonts and it should get installed with Wine. My guess is that you might not have installed it correctly or don't have `$WINE_FONT_DIR` set.
