### ISSUE TITLE
mfplat no longer working since commit 182dd174431c8cf669ae69d40dfb1819a214a8c2

### ISSUE THREAD

**Issue by adolfintel** [ValveSoftware/wine#198]
I noticed that several games started crashing or no longer start on recent builds of experimental.

I bisected the problem to commit 182dd174431c8cf669ae69d40dfb1819a214a8c2, which seems to have completely broken mfplat for me. The commit right before it still works perfectly fine.

I'm using Arch Linux with kernel 6.5.4 and a 6900xt with Mesa 23.3 built from source.

In case it helps, I have both dav1d and lib32-dav1d installed (version 1.2.1 from official repos) and gstreamer, lib32-gstreamer version 1.22.5. Removing gstreamer-vaapi also gets rid of the problem so it's related to hardware decoding.

**Comment by ivyl** [comment]
I've brought the discussion back to https://github.com/Frogging-Family/wine-tkg-git/issues/1072

This doesn't affect full Proton builds used via the runtime that are also using the shipped gstreamer. It's for standalone wine build using system gstreamer.
