### ISSUE TITLE
LibX11 1.8.2+ regression for "exotic" keyboard layout

### ISSUE THREAD

**Issue by aeris** [ValveSoftware/wine#199]
Since libx11 1.8.2, [a fix](https://gitlab.freedesktop.org/xorg/lib/libx11/-/commit/1c04ac514196db5e2255d99635fb6e3c36be330d) generates a regression on wine/proton for people using "exotic" layout keyboard like at least bepo.

Some keys are now wrongly affected (`é` become `è` and `è` no more detected, game change mapping on restart from `é` to `=`, etc).
Seems something on wine/proton was previously ok with a libx11 bug but now react in a strange maner with a proper fix.

Reverting the libx11 commit on 1.8.2+ (tested on 1.8.2, 1.8.6 and 1.8.7) restore the previous wine/proton behavior.
Weird behavior tested on Proton 8.0.4, and seems vanilla wine 8.17 is no more affected.

Corresponding issue on libx11 is [here](https://gitlab.freedesktop.org/xorg/lib/libx11/-/issues/179)

**Comment by kisak-valve** [comment]
Hello @aeris, this is a downstream fork of wine found in Proton. Looking over https://gitlab.freedesktop.org/xorg/lib/libx11/-/issues/179 and https://bugs.winehq.org/show_bug.cgi?id=53991, it looks like you've reported this fairly well in the bug trackers of the more relevant projects.

This issue should be evaluated and resolved between the devs of one of those two projects, and there's no real point in tracking it here as well.
