### ISSUE TITLE
Unity-based FPS Games have mouse jumping.

### ISSUE THREAD

**Issue by AmandaCameron** [ValveSoftware/wine#20]
As mentioned in [This comment for Subnautica](https://github.com/ValveSoftware/Proton/issues/79#issuecomment-419674039) there's some mouse issues where there's unexpected movement during mouse button presses. I'm experiencing a very similar issue in Stationeers (APPID: 544550) so I suspect it's got something to do with unity3d, which both games use.

**Comment by kisak-valve** [comment]
Hello @AmandaCameron, please copy your system information from steam (`Steam` -> `Help` -> `System Information`) and put it in a [gist](https://gist.github.com/), then include a link to the gist in this issue report. Additionally, what model mouse are you using?

**Comment by AmandaCameron** [comment]
Appologies:

[System Info](https://gist.github.com/AmandaCameron/ab3fe63f2b7b16764c5eddbfcffa4e6c)

The issue happens with both the [UHURU Bluetooth Mouse](https://smile.amazon.com/gp/product/B019MR4Y3U/) as well as the touch-pad built into my laptop.

**Comment by kisak-valve** [comment]
There's no particular reason to track this separately in the wine issue tracker instead of the Proton issue tracker, so I've transferred this issue to https://github.com/ValveSoftware/Proton/issues/1418.
