### ISSUE TITLE
RtlGenRandom MAX_CPUS wine cherrypick

### ISSUE THREAD

**Issue by jeremiahar** [ValveSoftware/wine#203]
Hi, is it possible to cherry pick the one liner commit https://github.com/wine-mirror/wine/commit/369e0cfae6052937ef6b90e8c9fe916ea6765d9b ?

Many games don't work on systems with > 64 cores on proton >= 6.3 because the buffer size is too small which causes RtlGenRandom to fail.

Ex: Old School Runescape login crashes with this log because BCryptGenRandom internally calls RtlGenRandom, which fails:
```
444290.316:0128:0178:fixme:bcrypt:BCryptGenRandom ignoring selected algorithm
444290.316:0128:0178:fixme:bcrypt:BCryptGenRandom called with unsupported parameters, returning error
```

Thanks.

**Comment by ivyl** [comment]
Done, thanks!

The change should show up in bleeding edge in 15 min or so and then the next experimental release.
