### ISSUE TITLE
how to compile

### ISSUE THREAD

**Issue by daktras420** [ValveSoftware/wine#204]
i do apologize in many ways i am still a newb but how do we compile this project?. the generic readme says to compile 
./config
make
make install
i am pretty sure you have another way to do the compile and install since there is no config file to use or i am greatly misunderstanding something. thank for in advance for your help.
i am attempting to leave the frogging family project and just compile projects like wine and proton straight from source. and a wine that is used outside of steam but with all the gaming enhancements you the valve community are continuously working on so when i saw this project i really wanted to put it to use.its a dream come true.

**Comment by kisak-valve** [comment]
Hello @daktras420 you've come across a downstream fork of wine used by Proton. This fork of wine is not intended to be used as a standalone component and the easiest way to get it is alongside the Proton builds distributed by Steam. If you want to build wine by itself, consult the upstream wine project's documentation.

That written, you can find Proton's general build instructions at https://github.com/ValveSoftware/Proton#building-proton.
