### ISSUE TITLE
Raw Mouse input not working correctly

### ISSUE THREAD

**Issue by Anti-Ultimate** [ValveSoftware/wine#21]
Using Wine and attempting to play any game using Raw Input results in the game having a completely different sensitivity than on Windows with same settings.
Tested using Overwatch, which uses Raw Mouse Input by default.

Raw Input works on any native port (I have the same sensitivity when using Raw Input in TF2 on Windows and Linux), but not on Wine.

I have already disabled any mouse acceleration on GNOME:

> Keyboard Control:
>   auto repeat:  on    key click percent:  0    LED mask:  00000002
>   XKB indicators:
>     00: Caps Lock:   off    01: Num Lock:    on     02: Scroll Lock: off
>     03: Compose:     off    04: Kana:        off    05: Sleep:       off
>     06: Suspend:     off    07: Mute:        off    08: Misc:        off
>     09: Mail:        off    10: Charging:    off    11: Shift Lock:  off
>     12: Group 2:     off    13: Mouse Keys:  off
>   auto repeat delay:  500    repeat rate:  33
>   auto repeating keys:  00ffffffdffffbbf
>                         fadfffefffedffff
>                         9fffffffffffffff
>                         fff7ffffffffffff
>   bell percent:  50    bell pitch:  400    bell duration:  100
> Pointer Control:
>   acceleration:  0/1    threshold:  0
> Screen Saver:
>   prefer blanking:  yes    allow exposures:  yes
>   timeout:  0    cycle:  0
> Colors:
>   default colormap:  0x20    BlackPixel:  0x0    WhitePixel:  0xffffff
> Font Path:
>   /usr/share/fonts/X11/misc,/usr/share/fonts/X11/Type1,built-ins
> DPMS (Energy Star):
>   Standby: 0    Suspend: 0    Off: 0
>   DPMS is Enabled
>   Monitor is On

https://www.reddit.com/r/wine_gaming/comments/9g9br6/disable_mouse_acceleration_in_overwatch/
Someone told me it's possible to make Wine use SDL for getting Raw Mouse Input instead of X11 itself. It would be great if you guys can patch this in somehow, as it would also help Wayland.

**Comment by Anti-Ultimate** [comment]
More info on this: It seems that Raw Mouse Input on Wine used to work before most distros ended up shipping libinput instead of the old xf86-evdev-input driver.

**Comment by swex** [comment]
Not sure if it worked with eudev. You can try to disable libinput for your mouse in Xorg.conf
here is related issue in proton repo: https://github.com/ValveSoftware/Proton/issues/408
Looks like raw input work is ongoing in upstream wine repo (already in wine 3.15) see:
https://source.winehq.org/git/wine.git/commit/85d5fc23b4cf6d369115802725e211d0c1195ccf
https://source.winehq.org/git/wine.git/commit/9e4e594972b0b01beb94e6f143ea46643205bf0b
https://source.winehq.org/git/wine.git/commit/6f3fb8c3f2061743f7f4b3c58bd00063949e51ea
https://source.winehq.org/git/wine.git/commit/c26de97ecc24d5a1edc912c88fd634e6679d58b2
https://source.winehq.org/git/wine.git/commit/44551cfe19f93fffb515b082871a35ae58c09fc2
https://source.winehq.org/git/wine.git/commit/e745a482d187920b4f87ee2ab7ed7f4eb37c268f

**Comment by Anti-Ultimate** [comment]
I was already using 3.15 with esync.

I understand Wine prolly doesn't want to depend on many external libraries, but they already use SDL2 for controllers. I assume someone who knew what he was doing could easily rewrite it to use SDL instead of getting it directly from evdev drivers.

**Comment by kisak-valve** [comment]
Hello @Anti-Ultimate, this issue should be taken to the [upstream wine bug tracker](https://bugs.winehq.org/).
