### ISSUE TITLE
MapViewOfFile3 alignment and/or NtMapViewOfSection(Ex) alignment strictness

### ISSUE THREAD

**Issue by jfmu** [ValveSoftware/wine#212]
Hi, i just want to relay to you a thing we discovered in ntdll.
https://bugs.winehq.org/show_bug.cgi?id=56161

In short. NtMapViewOfSection(Ex) they should ignore alignment at all when MEM_REPLACE_PLACEHOLDER is in the flags.
This prevents certain .net 7 apps from starting up. In my case only very big self-contained ones. 

Look at this "hack", which is actually how it should be done, in the other guys thread: 
https://bugs.winehq.org/show_bug.cgi?id=56122
https://bugs.winehq.org/attachment.cgi?id=75835

Kind regards

**Comment by kisak-valve** [comment]
Hello @jfmu, this doesn't look like a Proton-specific issue. The upstream bug tracker is the correct place to discuss this issue.
