### ISSUE TITLE
makedep: error: open wine/vulkan.h : No such file or directory

### ISSUE THREAD

**Issue by AndiMustafaj** [ValveSoftware/wine#213]
After have: "autoconf" and "./configure --enable-win64" configuration process fails with the error string "makedep: error: open wine/vulkan.h : No such file or directory".
Am i doing something wrong?

**Comment by rbernon** [comment]
You need to use Proton build system or do the same thing it does: https://github.com/ValveSoftware/Proton/blob/experimental_8.0/Makefile.in#L490

This is only for Proton's fork of Wine, and upstream Wine doesn't need that, but you need to get its sources at https://gitlab.winehq.org/wine/wine instead.
