### ISSUE TITLE
Wine refuses to launch games from NTFS drive

### ISSUE THREAD

**Issue by Her0brineCreeper** [ValveSoftware/wine#223]
### The problem
I have a dual-boot environment with one NTFS-formated hard drive with my games, so I can launch them from both Windows and Linux. The drive is automatically mounted at boot using an /etc/fstab entry with the default settings. This means all files and folders are owned by root:root with 777 permissions so all users can read and write the drive.

![grafik](https://github.com/ValveSoftware/wine/assets/56844781/7c253e2a-6e0c-4958-987d-957cf24fdb5a)

However, wine (proton) refuses to launch games from this drive with the following log:
```
======================
Proton: 1709844556 experimental-9.0-20240307b
SteamGameId: 945360
Command: ['/mnt/01D4670B74BF1CD0/Programme/SteamLibrary/steamapps/common/Among Us/Among Us.exe']
Options: {'forcelgadd'}
depot: 0.20240212.77547
pressure-vessel: 0.20240212.0 scout
scripts: 0.20240212.0
sniper: 0.20240212.77547 sniper 0.20240212.77547
Kernel: Linux 5.15.0-100-generic #110-Ubuntu SMP Wed Feb 7 13:27:48 UTC 2024 x86_64
Language: LC_ALL None, LC_MESSAGES None, LC_CTYPE None
Effective WINEDEBUG: +timestamp,+pid,+tid,+seh,+unwind,+threadname,+debugstr,+loaddll,+mscoree
======================
wineserver: /mnt/01D4670B74BF1CD0/Programme/SteamLibrary/steamapps/compatdata/945360/pfx is not owned by you
wine: '/mnt/01D4670B74BF1CD0/Programme/SteamLibrary/steamapps/compatdata/945360/pfx' is not owned by you
```

### Workaround
The issue can be fixed by mounting the drive as your user by adding the following to the mount parameters in /etc/fstab:
`uid=1000,gid=1000 (replace 1000 with your user/group-id)`

### Proposed solution
Wine should check if the user has proper permissions to access the folder instead of checking for ownership.

**Comment by kisak-valve** [comment]
Hello @Her0brineCreeper, noted at https://github.com/ValveSoftware/steam-for-linux/blob/master/RelNotes.md#installation, sharing Steam library folders between OSes is not supported and can lead to undefined behavior.

Upstream wine does not allow wineprefixes to be owned by another system user to avoid an entire category of hard to diagnose issues and Proton inherits upstream's behavior. This specific issue is being tracked at https://github.com/ValveSoftware/Proton/issues/4820.

Closing as a duplicate.
