### ISSUE TITLE
Crash in opengl32 when SteamGameId environment variable isn't set

### ISSUE THREAD

**Issue by descawed** [ValveSoftware/wine#228]
I was recently using Proton Experimental in the terminal to run some Morrowind mod tools, and I found that several of the tools were crashing when they tried to display a GUI. I tracked this down to the [`fixup_shader` function in opengl32](https://github.com/ValveSoftware/wine/blob/bleeding-edge/dlls/opengl32/wgl.c#L1347), which was dereferencing a null pointer due to using the `SteamGameId` environment variable without checking if it was set. I'm not sure if it's considered required for `SteamGameId` to be set, but the [stable version of this code](https://github.com/ValveSoftware/wine/blob/proton_9.0/dlls/opengl32/wgl.c#L1314) properly checks that the value is not null, so this seems to me like a regression.

I would normally try to submit a PR myself for a small change like this, but testing it seems like it might be somewhat involved; I'm not sure how I would go about configuring Proton to use my custom build of wine.

**Comment by ivyl** [comment]
This is no fixed in bleeding edge and will be a part of the next experimental release. Thanks!
