### ISSUE TITLE
some wow64 funcs are not working for wg_parser

### ISSUE THREAD

**Issue by peterjc123** [ValveSoftware/wine#232]
Fixes: #230 #231

**Comment by kisak-valve** [comment]
Hello @peterjc123, you've come across a downstream fork of wine used in Proton. These merge requests look like they should be reviewed and merged into upstream wine (https://gitlab.winehq.org/wine/wine/), and afterwards, if this is needed to fix a game with Proton, you can make a request to backport the accepted commits to Proton's variant of wine.

**Comment by peterjc123** [comment]
@kisak-valve Sorry for posting them here. I'll try to get it to upstream wine.

**Comment by peterjc123** [comment]
@kisak-valve After a second look, it seems that #230 only works for proton-wine, since the argument `flags` doesn't appear in upstream wine.

**Comment by peterjc123** [comment]
@kisak-valve #231 is similar, since these args `flags` and `uri` are only available in proton-wine. That's why those changes are needed in this repo, not the upstream wine.

**Comment by peterjc123** [comment]
@kisak-valve And there is another patch, https://github.com/ValveSoftware/wine/pull/233. I've checked that it doesn't apply for upstream wine.
