### ISSUE TITLE
[fshack] Switching a game to fullscreen may clip the mouse to the wrong monitor

### ISSUE THREAD

**Issue by kakra** [ValveSoftware/wine#24]
When I'm running a game on my second monitor and switch it to fullscreen, the mouse cursor is clipped to the primary screen but the game is resized to cover the secondary screen.

It works correctly for games displayed only on the primary screen.

**Tested with:** Path of Exile (CoInitialize patch applied so it can work in DX11 mode)

Setup your window manager to force the window to the secondary screen. Start the game, press Alt+Enter, the games successfully switches into fullscreen on the second monitor. But now the mouse cursor is clipped to the primary monitor.

I think that multi-monitor support in wine is somewhat buggy. Without making kwin forcing the game to the second monitor, it will display always on the primary monitor (happens with standard wine, too). Since this is a mouse-and-keyboard game, I'd like it to display on the desktop monitor, not the TV. TV is already set as the primary X11 monitor because otherwise many games (native and SteamPlay) would display on the wrong monitor.

**Comment by zzhiyi** [comment]
Confirmed. Patch https://github.com/zzhiyi/wine/commit/2e390db44147ae894c1be5898b8534c84ac8b672 addresses this issue. This patch required many other commits to be functional.

**Comment by zzhiyi** [comment]
Proton 5.13 should fix this issue.
