### ISSUE TITLE
WINE without X11/XWayland (pure Wayland) can't find graphics driver

### ISSUE THREAD

**Issue by vanfanel** [ValveSoftware/wine#249]
Hello there,

I've just built latest stable WINE (9.15) and also latest stable WINE sources from gitlab (https://gitlab.winehq.org/wine/wine/), and I get identical results when trying to load any program with it:
```
0148:err:winediag:nodrv_CreateWindow Application tried to create a window, but no driver could be loaded.
0148:err:winediag:nodrv_CreateWindow L"The graphics driver is missing. Check your build!"
```

WINE was successfully configured and built using the wine-wayland driver:
```
./configure --enable-win64 --without-x --with-wayland
--without-pulse --without-cups --without-gphoto --without-opencl --without-pcap --without-pcsclite --without-dbus --without-sane --without-oss --without-krb5 --without-netapi --without-capi --without-gettext --without-gnutls --enable-archs=x86_64,i386
```

As you can see in the configure log, the wayland driver is activated correctly:
[config.log](https://github.com/user-attachments/files/16678111/config.log)

And the wayland WINE driver is installed:
```
~/src/wine$ find /usr/local -name *winewayland* 
/usr/local/lib/wine/i386-windows/winewayland.drv
/usr/local/lib/wine/x86_64-unix/winewayland.so
/usr/local/lib/wine/x86_64-windows/winewayland.drv
```

I also tried forcing the driver loading using:
`WINEDEBUG=+wayland WINEDLLOVERRIDES="winewayland.drv=n" winecfg`

But that makes no difference.

Maybe mainline WINE is not ready for Wayland-only? Any ideas, please?

**Comment by kisak-valve** [comment]
Hello @vanfanel, you've come across a downstream fork of wine used in the Proton project. Report issues with upstream wine to the upstream wine devs (https://bugs.winehq.org/).
