### ISSUE TITLE
The Casting of Frank Stone crashes with assertion failed in wine

### ISSUE THREAD

**Issue by adolfintel** [ValveSoftware/wine#254]
I'm testing The Casting of Frank Stone (2223840) on the current bleeding-edge branch. The game crashes right after the initial logos with an assertion failed inside wine vulkan.

![image](https://github.com/user-attachments/assets/e075c882-95fe-46c7-9cd1-b7bf81cc2725)

Tested with
* Arch Linux, Kernel 6.10
* AMD Radeon 6900XT, Mesa 24.3 (current master)
* Valve wine, bleeding-edge branch (also crashes with current wine mainline)

**Comment by kisak-valve** [comment]
Hello @adolfintel, there's no point in tracking this separately from https://github.com/ValveSoftware/Proton/issues/8058. Closing in favor of the compatibility report on the Proton issue tracker.

Running the variant of wine used as a component of Proton as an independent build is also generally not supported.

**Comment by adolfintel** [comment]
My bad, it looks like we opened the issue around the same time.
