### ISSUE TITLE
Merge crypt32 patches from wine 3.17

### ISSUE THREAD

**Issue by ryao** [ValveSoftware/wine#26]
https://github.com/wine-mirror/wine/commits/master/dlls/crypt32

The patches from September 25 to September 27 fix a segfault in crypt32 that affects Rise of Nations:

https://github.com/ValveSoftware/Proton/issues/298

It would be nice to cherrypick them into Proton's wine so that Rise of Nations and anything else that hits it won't need end users to install the native crypt32 DLL as a workaround.

**Comment by ryao** [comment]
More specifically, this patch is probably the only one that is needed, but I'd prefer to just cherry pick the set:

https://github.com/wine-mirror/wine/commit/d18d38bc98006ef7c3c34e8e4e744e3768835735#diff-151a1558a85be7681ce2eb28d95fb63e

**Comment by d10sfan** [comment]
Looks like the new 3.16-2 has these fixes in it?

**Comment by kisak-valve** [comment]
Closing per https://github.com/ValveSoftware/wine/commit/ba61ebe15cc8d7974498415a6a4e46d9ed98ebb1.
