### ISSUE TITLE
Any patch sets available?

### ISSUE THREAD

**Issue by DarkDefender** [ValveSoftware/wine#3]
I know that you guys have already stated that everything that will be accepted upstream, will be pushed upstream.

However I'm wondering if there are any easily available patch sets that we can apply ourselves to upstream wine. I'm asking because there are a few very old games that I run with wine and I would really like to use the "Scale fullscreen to native desktop resolution" patches for these games.

I guess I could just compile and use the wine version in this repo, but it would be easier for me with patch sets (because I can easily apply them to upstream wine with Gentoo portage).

Or perhaps these patches could be submitted to wine staging in the mean time?

**Comment by aeikum** [comment]
We don't plan to do this, but others are welcome to. The fullscreen scaling stuff is referred to in the code as the "fullscreen hack" or "fs hack", and most of it is restricted to winex11.drv, with some in winevulkan that you probably don't need for those old games.

**Comment by Lahvuun** [comment]
You can easily produce the patchset yourself using git:
```git format-patch wine-3.7..proton/proton_3.7```

This will output all the patches, which should then be put into ```/etc/portage/patches/app-emulation/wine-3.7```.
I should note that you'll have to delete ```####-HACK-user32-Replace-Wine-glass-with-generic-window-i.patch```, as portage fails to apply it due to it containing a binary diff.

**Comment by DarkDefender** [comment]
@aeikum I've tried out and it seems like the scaling doesn't work as intended for the older games I've tested. The window is scaled, but the content inside of it is not. So I only get a 320x200 (or so) area with actual content. I guess these games uses ddraw or something.

@Lahvuun thanks for the tip. I actually just copied the wine-9999 ebuild and pointed it at this repo. I guess that is easier.

**Comment by aeikum** [comment]
@DarkDefender Yeah, the fs hack only works for opengl (including wined3d) and vulkan (including dxvk) games. We have some work done for games that render with GDI, but it's not in Proton yet.

**Comment by DarkDefender** [comment]
@aeikum Ah, nice to hear that you are working on it for old games that uses GDI. Thank you so much!

Should I open an issue for it here like "Games using the old GDI render are not scaled correctly with fs hack"? Even if it is not fixed in the near future, I would be really happy if I could track the progress with a public issue here.

**Comment by mkljczk** [comment]
[I tried (removed changes from upstream)](https://github.com/m4sk1n/wine/tree/patches), sorry for ordering them in reverse order.

**Comment by Thaodan** [comment]
@m4sk1n  from which wine version are these patches? Can you rebase them to latest wine-staging?

**Comment by mkljczk** [comment]
From 3.7, I don't have enough time to maintain them, rebase to any version etc.…
