### ISSUE TITLE
fshack

### ISSUE THREAD

**Issue by Thaodan** [ValveSoftware/wine#34]
If I understand it right this hack is to ensure that the game can be scaled up from his res to the target res of the monitor?
Which patches where applied to upstream to do this?

**Comment by aeikum** [comment]
A lot. Most of them are in winex11.drv, some in winevulkan. Shouldn't be too hard to find them in a log of those two directories.

**Comment by Thaodan** [comment]
It's not that easy to find. I hope valve prevents that their wine fork will be a pile of hacks like wine stating is but better.
