### ISSUE TITLE
Need to backport high core count fix from wine 4.0 rc1

### ISSUE THREAD

**Issue by GloriousEggroll** [ValveSoftware/wine#35]
https://github.com/wine-mirror/wine/commit/ed75a7b3443e79f9d63e97eeebcce2d2f40c507b#diff-556449596eac325214e3d355dfaa9826
https://github.com/wine-mirror/wine/commit/b9af36933fdf47cbbe139626e98750da72142dce#diff-556449596eac325214e3d355dfaa9826
https://github.com/wine-mirror/wine/commit/3c329e28d9ffabacdf1a3075a1dab27f68b1a9fe#diff-556449596eac325214e3d355dfaa9826

these fix the high corecount issue with games like skyrim se and fallout 4 hanging infinitely at save loading/new game loading on systems with processors like the Threadripper 1950x. also fixes the neverwinter launcher.  tested and working on my custom build.

**Comment by Thaodan** [comment]
What about rebasing onto wine anyway?
In the end its more work to always cleanup.

**Comment by NickZ** [comment]
If you've already made a custom build, why not submit a PR?

**Comment by aeikum** [comment]
These patches are included in Proton 4.2-1. Is anyone opposed to closing this issue?
