### ISSUE TITLE
[Mac OS] Build is broken

### ISSUE THREAD

**Issue by 3t0n** [ValveSoftware/wine#4]
Please update with [patch](https://github.com/wine-mirror/wine/commit/565c2dcf2aef1a555ff1025f230b4708df24d311#diff-5ee30cec6e041e568b5375e809d4b351) to fix Mac OS build:

**Comment by aeikum** [comment]
Thanks, will do.

**Comment by aeikum** [comment]
This was picked as 16a625e6638308f500fb55c3ca7f87cb968c796e.
