### ISSUE TITLE
Building fails

### ISSUE THREAD

**Issue by Ahmed-E-86** [ValveSoftware/wine#41]
Building always fails with this error:
`fatal error: gnutls26/gnutls.h: No such file or directory`

libgnutls28-dev is installed, and I have no clue why I get this message!
What can I do to avoid this error?

**Comment by kakra** [comment]
Well, maybe because gnutls26 is required but you installed gnutls28? If this isn't just a typo...

But I think it should build with gnutls30 also. There was a commit that addressed building with both gnutls26 and gnutls30 but linking against either of these at runtime.

**Comment by aeikum** [comment]
That header is provided in `proton.git/contrib/include`.  It is provided to Wine's configure with CFLAGS in the makefile. Are you using the makefile to build? Is your proton git branch up to date?

**Comment by Ahmed-E-86** [comment]
I am trying to use this branch https://github.com/jzengc/wine/tree/proton_3.16_mf

What should I change for this to work?

**Comment by aeikum** [comment]
You need to build these Wine branches from within https://github.com/ValveSoftware/Proton/ . You can't build them stand-alone.

**Comment by kisak-valve** [comment]
jzengc has an equivalent Proton git repository. In any case, issues with forks of Proton should be reported to the fork.

**Comment by Ahmed-E-86** [comment]
> jzengc has an equivalent Proton git repository. In any case, issues with forks of Proton should be reported to the fork.

I am sorry about that, but I couldn't find Issue tab with the forks, so I didn't know where to report this issue.

**Comment by pchome** [comment]
Faced similar issue.

@ahmed-elsayed2017 
> What can I do to avoid this error?

Execute in an empty directory:
```
git init
git remote add proton git://github.com/ValveSoftware/Proton.git
git fetch --depth=1 proton proton_3.16
git checkout proton/proton_3.16 -- contrib

mkdir -p empty

diff -urN empty contrib > gnults26-include.patch
```
Then:
```
cd /your/wine/build
patch -p1 < /path/to/gnults26-include.patch
```

@aeikum 
> You can't build them stand-alone.

I have all required modules installed system-wide, except `lsteamclient`. If it possible to split `lsteamclient` into separate repo -- it would be great.
But despite that wine builds fine for me, w/ patch mentioned above.

**Comment by kakra** [comment]
@pchome @aeikum Yes, a split-out lsteamlib would be great... Could the subdir just be moved into its own repository? Or does it have deps across the subdir boundary (except wine itself)?

**Comment by Ahmed-E-86** [comment]
Building inside Proton makes a wine build that doesn't run.

Building with the patch @kakra  mentioned gives the same with this error message at the end:
0009:err:module:load_library somehow failed to load steamclient

It is useless!
