### ISSUE TITLE
From wine-staging: [PATCH] kernel32: Correct ReplaceFileW behaviour

### ISSUE THREAD

**Issue by Commaster** [ValveSoftware/wine#45]
Please apply the recently staged bugfix for ReplaceFile behavior when trying to replace own executable. (Affects the Warframe launcher self-update at least): https://github.com/wine-staging/wine-staging/commit/8b930aea2fe08d845dc9860001718cd0bbe7e67f
Thank you.

**Comment by aeikum** [comment]
We'll look into it.

**Comment by Commaster** [comment]
Patch has been applied upstream with the 4.6 release:
https://github.com/wine-mirror/wine/commit/04ccd995b1aec5eac5874454a320b37676b69c42
https://source.winehq.org/git/wine.git/?a=commit;h=04ccd995b1aec5eac5874454a320b37676b69c42

**Comment by aeikum** [comment]
This is included in 4.2-3. c0c406e495274953e86a84b91b8fe41566ba258f
