### ISSUE TITLE
rebase to wine 3.14

### ISSUE THREAD

**Issue by cjwijtmans** [ValveSoftware/wine#5]
It has 
"Support for DXTn texture decompression."
And some fixes for saving games.(since wine 3.11, https://source.winehq.org/git/wine.git/patch/ff7c2c51718e8f64c9b708847f3a322bd136eb75)

https://www.winehq.org/announce/3.14

**Comment by aeikum** [comment]
Yes, we have plans to upgrade Proton in the future. Working out launch kinks for now.
