### ISSUE TITLE
Loader lock might never be released in GetModuleHandleExW()

### ISSUE THREAD

**Issue by imaami** [ValveSoftware/wine#61]
[The return statement on line 482 in `dlls/kernel32/module.c`](https://github.com/ValveSoftware/wine/blob/aebdb22bb57128a5f38cd07d3952f1eb62e44817/dlls/kernel32/module.c#L482) may be executed without the loader lock set earlier never being released.

**Comment by kisak-valve** [comment]
Hello @imaami, there's no value in tracking this issue with both an issue report and a pull request because Github combines them and this can be discussed on the pull request. Closing in favor of #62.

**Comment by imaami** [comment]
> Hello @imaami, there's no value in tracking this issue with both an issue report and a pull request because Github combines them and this can be discussed on the pull request. Closing in favor of #62.

Thanks for the info, I didn't know Github does that. :)
