### ISSUE TITLE
fsync patches added?

### ISSUE THREAD

**Issue by SR-dude** [ValveSoftware/wine#68]
Does the Proton 4.11 branch have the fsync patches already applied?

**Comment by kisak-valve** [comment]
Hello @SR-dude, yes.

https://github.com/ValveSoftware/wine/search?q=fsync&type=Commits.

**Comment by SR-dude** [comment]
Thanks. I suppose in order for this to work, you would need FUTEX_WAIT_MULTIPLE added in the kernel. But, what about the patches to glibc, namely pthread_mutex_lock_any().  Would that be needed as well?

**Comment by kakra** [comment]
@SR-dude Currently no, the patches in wine-proton directly do the syscall by ID and do not use glibc thread functions, as far as I understood. Adding the glibc patches would only benefit other software which wait on many threads.
