### ISSUE TITLE
Modified version of staging patch winex11.drv-mouse-coords available

### ISSUE THREAD

**Issue by GloriousEggroll** [ValveSoftware/wine#78]
After some discussion regarding this patchset with the patch creator regarding this bug:

https://bugs.winehq.org/attachment.cgi?id=66387

The author has made an updated version compatible with proton. There is one block that needs modification, which I've applied here:

https://bugs.winehq.org/show_bug.cgi?id=46309#c12

The reason I'm bringing this up is because this bug also affects Origin, and the patch allows origin to be freely dragged smoothly without issue.

**Comment by aeikum** [comment]
Hey @GloriousEggroll, this patch was included in 5.0-4 as 69ee005adf498b87a6be464e98c61730d32896c9. Thanks for the suggestion!
