### ISSUE TITLE
problem with Al Qaeda Hunting 3D

### ISSUE THREAD

**Issue by soredake** [ValveSoftware/wine#87]
https://www.myabandonware.com/game/al-qaeda-hunting-3d-dwh
without WINE_FULLSCREEN_INTEGER_SCALING:
![Screenshot_20200329_165826](https://user-images.githubusercontent.com/5204968/77850943-97b32580-71de-11ea-9258-ea617244a7a9.png)

with WINE_FULLSCREEN_INTEGER_SCALING only black screen is shown

[al-3d.log](https://github.com/ValveSoftware/wine/files/4414335/al-3d.log)

**Comment by kisak-valve** [comment]
From the log:
`Wine TkG 5.5 is a testing version containing experimental patches.`
`Please don't report bugs about it on winehq.org and use https://github.com/Tk-Glitch/PKGBUILDS/issues instead.`

**Comment by soredake** [comment]
That's a problem with fshack and integer scaling, dunno where to report.
