### ISSUE TITLE
Solar System Explorer by Maris Multimedia not running (Quick Time) error

### ISSUE THREAD

**Issue by Brido17** [ValveSoftware/wine#90]
I'm new to Linux / Wine and have been trying to install some old favourite games of mine. While this software installed properly, running it is an issue due to a Quick Time error as shown. Any advice would be welcome and much appreciated.

![Screenshot from 2020-04-11 13-56-53](https://user-images.githubusercontent.com/61377931/79044351-844f8380-7bfc-11ea-806e-010417c48f61.png)
![Screenshot from 2020-04-11 13-19-25](https://user-images.githubusercontent.com/61377931/79044357-8b769180-7bfc-11ea-98ee-6829d9c8d75a.png)
![Screenshot from 2020-04-11 14-05-49](https://user-images.githubusercontent.com/61377931/79044553-a7c6fe00-7bfd-11ea-8ff7-4c127824dbab.png)

**Comment by kisak-valve** [comment]
Hello @Brido17, you've found a fork of the wine project which is used inside of [Proton](https://github.com/ValveSoftware/Proton). Please report issues with wine to https://bugs.winehq.org/ for the upstream devs to ponder.

**Comment by Brido17** [comment]
Hi kisak-valve, thanks for your prompt reply and for sign posting - - appreciated. Nothing worse than going around in circles.
