### ISSUE TITLE
GCC 10 compatibility

### ISSUE THREAD

**Issue by loathingKernel** [ValveSoftware/wine#93]
Please cherry pick the following commits for compatibility with GCC 10

https://github.com/wine-mirror/wine/commit/5740b735cdb44fb89a41f3090dcc3dabf360ab41
https://github.com/wine-mirror/wine/commit/fba65a153759dd60f470fe9a787f074cbf0f7ea8
https://github.com/wine-mirror/wine/commit/453980e13015e20dd551531be69b3361b63f22b1
https://github.com/wine-mirror/wine/commit/e402fdf364fc76838ba4e11a11fef3c552110639
https://github.com/wine-mirror/wine/commit/cc7f698b8245a48669d248569e7589ff824f2c70
https://github.com/wine-mirror/wine/commit/c13d58780f78393571dfdeb5b4952e3dcd7ded90
https://github.com/wine-mirror/wine/commit/93888fbb3e4d973f5878a0aab16a9d64fb73a764
https://github.com/wine-mirror/wine/commit/4a91eb362666b3af549c48b95e093051756628e0
https://github.com/wine-mirror/wine/commit/bc51c5d589de709e1d393b58b0cc5985c78061ac
https://github.com/wine-mirror/wine/commit/388348ddbf7d138fed3a6fe48bf6666a95ef3528
https://github.com/wine-mirror/wine/commit/44e69405adcdc98d6b0777e6c0acb2697d776ef8

**Comment by kisak-valve** [comment]
Hello @loathingKernel, these commits should have come from upstream with the Proton 5.13-1 update. Please retest.

**Comment by loathingKernel** [comment]
@kisak-valve I can verify that wine shipped with proton 5.13 builds just fine now with GCC 10. Thank you!
