### ISSUE TITLE
Unity games deviceUniqueIdentifier not unique - Update to Wine 5.10

### ISSUE THREAD

**Issue by dannyNK** [ValveSoftware/wine#97]
As per this issue here: https://bugs.winehq.org/show_bug.cgi?id=49160

In Unity games the [SystemInfo.deviceUniqueIdentifier](https://docs.unity3d.com/ScriptReference/SystemInfo-deviceUniqueIdentifier.html) is consistent across all wine users. This causes issues when trying to individually determine users.

Wine 5.10 appears to have an update to address this issue.

**Comment by kisak-valve** [comment]
More specifically, https://source.winehq.org/git/wine.git/commit/84857d27067afaa1ae5774afe27086332263bfb5 and possibly https://source.winehq.org/git/wine.git/commit/f516a23041b3871625764611321250f977fe750a are the commits involved.

**Comment by aeikum** [comment]
If what you need is those patches from Wine 5.10, then we will have some good news for you soon.

**Comment by kiranshila** [comment]
@dannyNK any reason not to just build for Linux? Should be straightforward for a unity game.

**Comment by dannyNK** [comment]
> @dannyNK any reason not to just build for Linux? Should be straightforward for a unity game.

Building a small Unity project for linux would be straightforward, but ours is a very complex project with many platform specific features which complicates the process of building for other platforms more than might be obvious. We also update our games with new features and content on a very regular basis so introducing a new platform increases the QA and submission workload for each update. 

We do listen to our customers, and if there is a strong demand it is something we may look into.

**Comment by myahenochs** [comment]
Every game with official support, especially ones like yours that pretty much every young person knows, helps our community grow and become more recognized.

That being said, if a Linux build would hinder new content and it works on Proton just fine, personally I'd rather have the content.

**Comment by kisak-valve** [comment]
Hello @dannyNK, with https://github.com/ValveSoftware/wine/commit/84857d27067afaa1ae5774afe27086332263bfb5 and https://github.com/ValveSoftware/wine/commit/f516a23041b3871625764611321250f977fe750a in Proton 5.13-1, I think we're good to go here. Please retest.
